global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'football-api'
    static_configs:
      - targets: ['api:3001']

  - job_name: 'football-ml'
    static_configs:
      - targets: ['ml:8000']
